baseURL = "https://kokosproduction.mk"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

languageCode = "en-us"
defaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Kokos Production"
    # Navbar Menus
    [[menu.main]]
    name    = "Home"
    url     = "/"
    weight  = 1
    [[menu.main]]
    name    = "About"
    url     = "about"
    weight  = 2
#    [[menu.main]]
#    name    = "Gallery"
#    url     = "gallery"
#    weight  = 3
    [[menu.main]]
    name    = "Contact"
    url     = "contact"
    weight  = 4
    [[menu.main]]
    name    = "Projects"
    weight  = 5
    [[menu.main]]         
     name    = "Our Projects"
     url = "projects"
     parent = "Projects"
     weight  = 1
    [[menu.main]]         
     name    = "Collaborations"
     url = "colabs"
     parent = "Projects"
     weight  = 2



    # Site Params
    [params]
    home = "Home"
    logo = "images/logo.png"
    button = "Continue Reading"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Airspace Hugo theme"
    author = "Themefisher"
    # Google Analitycs
    googleAnalitycsID = "Your ID"
    # contact form action
    contactFormAction = "https://formspree.io/f/xeqvndav" # contact form works with https://formspree.io
    
    # Banner Section
    [params.banner]
    enable  = true
    bgImage = "images/slider.jpg"
    heading = "WE ARE KOKOS PRODUCTION"
    description = "OUR CREATIVITY IS UNBRIDLED"
    # button
    btn     = true
    btnText = "Contact us"
    btnURL  = "https://www.facebook.com/Kokos-Produkcija-110477254195024/"
    
    # flip text
    [[params.banner.flipText]]
    title   = "VIDEO"
    [[params.banner.flipText]]
    title   = "PHOTOGRAHY"
    [[params.banner.flipText]]
    title   = "ANIMATION"
    
    # Homepage About Section
    [params.about]
    enable  = true
    title   = "ABOUT US"
    content = "Kokos Production is a video production company covering all phases of production from development, pre-production, production to post-production.<br>Our creative team is fully invested in each phase to provide the client with quality final products including video, photography, animation, multimedia, visual arts and text."
    image   = "images/about/about.jpg"
    
    # Call to Action
    [params.cta]
    enable  = true
    title   = "SO WHAT YOU THINK ?"
    content = "Get in touch with us to find out more"
    btnText = "Contact"
    btnURL  = "/contact"
    
    # Portfolio Section On Homepage
    [params.portfolio]
    enable  = true
    title   = "Latest Works"
    subtitle= "Showcase of latest works, including photography of events, as well as camera work and production for documentaries, commercials and music videos"
    
    # social icon
    [[params.socialIcon]]
    icon = "ion-social-facebook"
    url = "https://www.facebook.com/Kokos-Produkcija-110477254195024/"
    
    [[params.socialIcon]]
    icon = "ion-social-instagram"
    url = "https://www.instagram.com/kokosprodukcija"
    
    [[params.socialIcon]]
    icon = "ion-social-linkedin"
